package com.youngrich.oliveold.domain;

public enum CategoryDetailName {
    // 스킨케어
    SKIN_TONER, ESSENCE_SERUM_AMPULE, CREAM, LOTION, MIST_OIL, SKINCARE_SET,
    // 마스크팩
    SHEET_PACK, PAD_PACK, FACIAL_PACK, NOSE_PACK, PATCH,
    // 클렌징
    CLEANSING_FOAM_GEL, CLEANSING_OIL_BALM, CLEANSING_WATER_MILK, PEELING_SCRUB, CLEANSING_TISSUE_PAD, LIP_EYE_REMOVER,
    // 선케어
    SUNCREAM, SUNSTICK, SUNCUSHION, SUNSPRAY_PATCH, TANNING_AFTER_SUN,
    // 메이크업
    LIP_MAKEUP, BASE_MAKEUP, EYE_MAKEUP,
    // 네일
    REGULAR_NAIL, GEL_NAIL, NAIL_TIP_STICKER, NAIL_CARE,
    // 뷰티소품
    MAKEUP_TOOLS, SKINCARE_TOOLS, EYE_TOOLS, HAIR_BODY_TOOLS, GUASHA_NAIL_TOOLS, BEAUTY_DEVICES, BEAUTY_ACCESSORIES,
    // 향수/디퓨저
    WOMEN_FRAGRANCE, MEN_FRAGRANCE, UNISEX_FRAGRANCE, MINI_SOLID_FRAGRANCE, HOME_FRAGRANCE,
    // 헤어케어
    SHAMPOO_CONDITIONER, TREATMENT_PACK, HAIR_ESSENCE, HAIR_DYE_PERM, HAIR_TOOLS_BRUSH, HAIR_STYLING,
    // 바디케어
    BODY_LOTION_OIL, SHOWER_BATH, LIP_CARE, HAND_CARE, BODY_MIST, HAIR_REMOVAL_WAXING, DEODORANT,
    // 기타
    GIFT_SET, BABY_PRODUCTS
}
